apiVersion: v1
kind: ConfigMap
metadata:
  namespace: shinyproxy-apps
  name: shinyproxy-config
data:
  application.yml: |
    proxy:
      container-wait-time: 600000 # Wait up to 10 minutes for the app to be reachable
      container-backend: kubernetes
      kubernetes:
        namespace: shinyproxy-apps
        image-pull-policy: IfNotPresent
        pod-wait-time: 600000 # Time in milliseconds (e.g., 2 minutes)
      title: Kubernetes clustered Shiny platform  
      landing-page: /
      authentication: none

      specs:
        - id: 01_hello
          display-name: Hello shiny application
          description: Demonstration for a simple shiny app
          container-cmd: [ "R", "-e", "shinyproxy::run_01_hello()" ]
          container-image: openanalytics/shinyproxy-demo
        - id: 02_shiny_sliders
          display-name: Sliders shiny application
          description: Demonstration for a shiny app with sliders
          container-image: rocker/shiny:4.6.0
          container-cmd: [ "R", "-e", "shiny::runApp('/srv/shiny-server/05_sliders', host='0.0.0.0', port=3838)" ]
    server:
      port: 80
      useForwardHeaders: true
      forward-headers-strategy: native
      servlet:
        # shinyproxy no longer serves on a root path /
        # it serves on a hash path to enhance security when none authentication.
        context-path: /sIud2k8TAaEs
        session:
          # Automatically destroy local idle sessions quickly (e.g., 15 minutes)
          timeout: 15m
    logging:
      file:
        shinyproxy.log
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: shinyproxy-apps
  name: shinyproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shinyproxy
  template:
    metadata:
      labels:
        app: shinyproxy
    spec:
      containers:
      - name: shinyproxy
        image: openanalytics/shinyproxy:3.2.4 
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume
          mountPath: /opt/shinyproxy/application.yml
          subPath: application.yml
      volumes:
      - name: config-volume
        configMap:
          name: shinyproxy-config
          items:
          - key: application.yml
            path: application.yml
