apiVersion: v1
kind: Service
metadata:
  namespace: shinyproxy-apps
  name: shinyproxy-service
  labels:
    app: shinyproxy
spec:
  type: LoadBalancer
  selector:
    app: shinyproxy
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
